# https://kubernetes.io/ko/docs/concepts/services-networking/ingress
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
# https://kmaster.tistory.com/94#google_vignette
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.commonLabels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.annotation.backendProtocol | default "HTTP" | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.annotation.proxyConnectTimeout | default "10" | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.annotation.proxyReadTimeout | default "60" | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.annotation.proxySendTimeout | default "60" | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.annotation.proxyBodySize | default "8m" | quote }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }} # ingress 리소스를 어떤 ingress controller가 처리할 것인지 지정
  {{- if .Values.ingress.rules }}
  rules:
    {{- range .Values.ingress.rules }}
    - {{- if .host }}
      host: {{ .host }}
      {{- end }}
      http:
        paths:
        {{- range .http.paths }}
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ .backend.service.name }}
              port:
                number: {{ .backend.service.port.number }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}