apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-project
  namespace: argocd
spec:
  description: "Production environment project"

  sourceRepos:
    - "https://github.com/ym1085/sandbox-k8s-gitops.git"
    - "https://kubernetes.github.io/ingress-nginx"

  destinations:
    - namespace: "prod-order-ns"
      server: https://kubernetes.default.svc

    - namespace: "prod-user-ns"
      server: https://kubernetes.default.svc

    - namespace: "prod-ingress-nginx-ns"
      server: https://kubernetes.default.svc

    - namespace: "argocd"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
