kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: helm-cluster
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      # --- DEV ENV ---
      # Ingress
      - hostPort: 30080
        containerPort: 30080
        protocol: TCP
      - hostPort: 30443
        containerPort: 30443
        protocol: TCP

      # ArgoCD
      - hostPort: 30180
        containerPort: 30180
        protocol: TCP
      - hostPort: 30543
        containerPort: 30543
        protocol: TCP

      # --- STG ENV ---
      # Ingress
      - hostPort: 31080
        containerPort: 31080
        protocol: TCP
      - hostPort: 31443
        containerPort: 31443
        protocol: TCP
      # ArgoCD
      - hostPort: 31180
        containerPort: 31180
        protocol: TCP
      - hostPort: 31543
        containerPort: 31543
        protocol: TCP

      # --- PROD ENV ---
      # Ingress
      - hostPort: 32080
        containerPort: 32080
        protocol: TCP
      - hostPort: 32443
        containerPort: 32443
        protocol: TCP
      # ArgoCD
      - hostPort: 32180
        containerPort: 32180
        protocol: TCP
      - hostPort: 32543
        containerPort: 32543
        protocol: TCP
