apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-dev
  namespace: argocd
spec:
  description: "Dev infrastructure services"
  sourceRepos:
    - "https://kubernetes.github.io/ingress-nginx"
  destinations:
    - namespace: "ingress-nginx-dev"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "Deployment"
    - group: ""
      kind: "Service"
    - group: ""
      kind: "ConfigMap"
    - group: ""
      kind: "ServiceAccount"
    - group: "rbac.authorization.k8s.io"
      kind: "Role"
    - group: "rbac.authorization.k8s.io"
      kind: "RoleBinding"
