apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-prod
  namespace: argocd
spec:
  project: infra-prod
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.0
    helm:
      values: |
        controller:
          ingressClassResource:
            name: nginx-prod
            enabled: true
            controllerValue: "k8s.io/ingress-nginx-prod"
          service:
            type: NodePort
            nodePorts:
              http: 32080
              https: 32443
          admissionWebhooks:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
      - PruneLast=true
