apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-order-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "order-api=youngmin1085/order-service"
    argocd-image-updater.argoproj.io/order-api.update-strategy: "newest-build"
    argocd-image-updater.argoproj.io/order-api.allow-tags: "regexp:^stg-[a-f0-9]{7}$"
    argocd-image-updater.argoproj.io/order-api.helm.image-name: deployment.containers[0].image
    argocd-image-updater.argoproj.io/order-api.helm.image-tag: deployment.containers[0].tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: stg-project

  source:
    repoURL: https://github.com/ym1085/sandbox-k8s-gitops.git
    targetRevision: stg
    path: charts/order-service
    helm:
      valueFiles:
        - values-stg.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: stg-order-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
      - PruneLast=true
