# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
# https://kkamji.net/posts/argocd-application-declarative/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-order-service # Argo CD UI 및 CLI에서 식별할 애플리케이션의 고유 이름
  namespace: argocd # Argo CD 컨트롤러가 설치된 네임스페이스 (기본값은 보통 'argocd')
  annotations:
    argocd-image-updater.argoproj.io/image-list: "order-api=youngmin1085/order-service"
    argocd-image-updater.argoproj.io/order-api.update-strategy: "newest-build"
    argocd-image-updater.argoproj.io/order-api.allow-tags: "regexp:^dev-[a-f0-9]{7}$"
    argocd-image-updater.argoproj.io/order-api.helm.image-name: deployment.containers[0].image
    argocd-image-updater.argoproj.io/order-api.helm.image-tag: deployment.containers[0].tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: dev-project # 애플리케이션을 논리적으로 그룹화하는 프로젝트 이름 (RBAC 밎 접근 제어에 활용)

  # 배포할 소스(Git/Helm) 정보 설정
  source:
    repoURL: https://github.com/ym1085/sandbox-k8s-gitops.git # manifest 파일이 위치한 Git 저장소 URL
    targetRevision: dev # 추적할 브랜치, 태그 또는 커밋 해시 (master 브랜치 감시)
    path: charts/order-service # 저장소 내에서 Helm 차트나 k8s manifest가 위치한 상대 경로
    helm:
      valueFiles:
        - values-dev.yaml

  # 배포 대상(Target) 클러스터 및 NS 설정
  destination:
    server: https://kubernetes.default.svc # 클러스터의 API 서버 주소
    namespace: dev-order-ns # 애플리케이션을 배포할 네임스페이스

  # 동기화(Sync) 정책 설정
  syncPolicy:
    automated: # 자동 동기화 활:성화
      prune: true # Git에서 삭제된 리소스를 실제 클러스터에서도 자동 삭제할지 여부
      selfHeal: true # 클러스터 리소스가 수동으로 수정되어 Git과 달라졌을 때 자동으로 복구(동기화) 할지 여부
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
      - PruneLast=true
