apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: user-dev
  namespace: argocd
spec:
  description: "Dev user service (회원관리팀)"
  sourceRepos:
    - "https://github.com/ym1085/sandbox-k8s-gitops.git"
  destinations:
    - namespace: "user-dev"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "Deployment"
    - group: ""
      kind: "Service"
    - group: "networking.k8s.io"
      kind: "Ingress"
