{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.commonLabels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.annotation.backendProtocol | default "HTTP" | quote }} # 백엔드 Service 통신 시 사용할 프로토콜(HTTP, HTTPS, GRPC)
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.annotation.proxyConnectTimeout | default "10" | quote }} # 백엔드 연결 시도 후 연결이 완료 될때까지 기다리는 최대 시간
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.annotation.proxyReadTimeout | default "60" | quote }} # 백엔드로부터 응답을 읽기 시작한 후, 응답이 없을 때 대기할 시간
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.annotation.proxySendTimeout | default "60" | quote }} # 백엔드로 요청 데이터를 전송할 때 대기할 최대 시간
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.annotation.proxyBodySize | default "8m" | quote }} # 클라이언트가 업로드할 요청 본문 최대 크기 제한 (예: 파일 업로드 시 8MB 제한)
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }} # ingress 리소스를 어떤 ingress controller가 처리할 것인지 지정
  {{- if .Values.ingress.rules }}
  rules:
    {{- range .Values.ingress.rules }}
    - {{- if .host }}
      host: {{ .host }}
      {{- end }}
      http:
        paths:
        {{- range .http.paths }}
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ .backend.service.name }}
              port:
                number: {{ .backend.service.port.number }}
        {{- end }}
    {{- end }}
  {{- end}}
{{- end }}