{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.commonLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if and (eq $.Values.service.type "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end }}
